# Delifast Shopify App Configuration
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af955fe755967af3f8bc9a39e13ad1d5"
name = "delifast"
application_url = "https://delifast-public.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "read_orders,write_orders,read_fulfillments,write_fulfillments,read_customers,write_metafields,read_metafields"

[auth]
redirect_urls = [
  "https://delifast-public.onrender.com/auth/callback",
  "https://delifast-public.onrender.com/auth/login"
]
